using Squad.Sdk.Config;

namespace Squad.Sdk.Generation;

public sealed record GeneratedFile(string RelPath, string Content);

/// <summary>
/// Generates .squad/ markdown from a SquadConfig (squad.config.json).
/// This is the .NET equivalent of the TypeScript "squad build" pipeline.
/// </summary>
public static class SquadMarkdownGenerator
{
    private const string GeneratedHeader = "<!-- generated by squad build — do not edit -->\n\n";
    private static readonly HashSet<string> ProtectedFiles =
        new(StringComparer.OrdinalIgnoreCase) { "decisions.md", "decisions-archive.md", "history.md" };

    public static IReadOnlyList<GeneratedFile> Build(SquadConfig config)
    {
        var files = new List<GeneratedFile>();

        files.Add(new(".squad/team.md", GenerateTeamMd(config)));

        if (config.Routing != null)
            files.Add(new(".squad/routing.md", GenerateRoutingMd(config)));

        foreach (var agent in config.Agents)
            files.Add(new($".squad/agents/{agent.Name}/charter.md", GenerateCharterMd(agent, config)));

        return files;
    }

    private static string GenerateTeamMd(SquadConfig config)
    {
        var sb = new System.Text.StringBuilder(GeneratedHeader);
        sb.AppendLine($"# Squad Team — {config.Team.Name}\n");
        if (!string.IsNullOrEmpty(config.Team.Description))
            sb.AppendLine($"> {config.Team.Description}\n");

        sb.AppendLine("## Members\n");
        sb.AppendLine("| Name | Role | Charter | Status |");
        sb.AppendLine("|------|------|---------|--------|");
        foreach (var agent in config.Agents)
        {
            var name = char.ToUpper(agent.Name[0]) + agent.Name[1..];
            var role = agent.Role ?? agent.Name;
            sb.AppendLine($"| {name} | {role} | `.squad/agents/{agent.Name}/charter.md` | ✅ Active |");
        }
        return sb.ToString();
    }

    private static string GenerateRoutingMd(SquadConfig config)
    {
        var routing = config.Routing!;
        var sb = new System.Text.StringBuilder(GeneratedHeader);
        sb.AppendLine($"# Routing Rules — {config.Team.Name}\n");
        if (routing.DefaultAgent != null)
            sb.AppendLine($"**Default agent:** {routing.DefaultAgent}\n");

        sb.AppendLine("## Rules\n");
        foreach (var rule in routing.Rules)
            sb.AppendLine($"- `{rule.Pattern}` → {rule.Agent}");

        return sb.ToString();
    }

    private static string GenerateCharterMd(AgentConfig agent, SquadConfig config)
    {
        var sb = new System.Text.StringBuilder(GeneratedHeader);
        var name = char.ToUpper(agent.Name[0]) + agent.Name[1..];
        var role = agent.Role ?? agent.Name;
        sb.AppendLine($"# {name} — {role}\n");

        if (!string.IsNullOrEmpty(agent.Charter))
            sb.AppendLine(agent.Charter + "\n");

        if (!string.IsNullOrEmpty(agent.Model))
        {
            sb.AppendLine("## Model\n");
            sb.AppendLine($"**Preferred:** {agent.Model}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Returns true if all generated files match what is currently on disk.
    /// </summary>
    public static bool CheckDrift(string cwd, IReadOnlyList<GeneratedFile> files)
    {
        foreach (var file in files)
        {
            if (ProtectedFiles.Contains(Path.GetFileName(file.RelPath))) continue;
            var absPath = Path.Combine(cwd, file.RelPath.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(absPath)) return false;
            if (File.ReadAllText(absPath) != file.Content) return false;
        }
        return true;
    }

    /// <summary>
    /// Write generated files to disk, skipping protected files.
    /// </summary>
    public static void WriteFiles(string cwd, IReadOnlyList<GeneratedFile> files)
    {
        foreach (var file in files)
        {
            if (ProtectedFiles.Contains(Path.GetFileName(file.RelPath))) continue;
            var absPath = Path.Combine(cwd, file.RelPath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(absPath)!);
            File.WriteAllText(absPath, file.Content);
        }
    }
}
